### ISSUE TITLE
download history

### ISSUE THREAD

**Issue by ggrigon** [ggrigon/gopro-photo-of-day#1]
create a file to make a history of downloaded files, to avoid download the same file many times

**Comment by gustafsilva** [comment]
Hello @ggrigon , I would like to do this task :+1: 
Can i write this file in `JSON` format?

**Comment by ggrigon** [comment]
Hi @gustafsilva, 
My objective is to reduce the time for updates, for example when i run this script one time and download 1000 photos, for the next time i want to download only the newest pictures, so it should save time

**Comment by gustafsilva** [comment]
I thought about creating a file to store all URLs already downloaded.
Before downloading the images the file would be read, and only the images that do not have the URL in this file would be downloaded again.
I think that would solve this problem :rocket:
What do you think?

**Comment by ggrigon** [comment]
nice, it's gonna be a nice feature, exactly what i wanted

**Comment by gustafsilva** [comment]
Good, i'll start doing :rocket:
